included:
    - iOSEngineerCodeCheck
    - iOSEngineerCodeCheckTests
    - iOSEngineerCodeCheckUITests

opt_in_rules:
  - anyobject_protocol
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - fatal_error_message
  - file_name_no_space
  - file_types_order
  - implicitly_unwrapped_optional
  - indentation_width
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - static_operator
  - switch_case_on_newline
  - toggle_bool
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases

disabled_rules:
  - line_length

identifier_name:
    min_length: 1
    max_length: 50

trailing_comma:
  mandatory_comma: true
  
trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 3

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: 
    - iOSEngineerCodeCheckUITests
    - iOSEngineerCodeCheckTests
